import React, { useState } from 'react';
import { 
  Sparkles, 
  CheckSquare, 
  CheckCircle2, 
  ListChecks, 
  ShieldCheck, 
  Copy, 
  Check, 
  Download, 
  Share2, 
  FileText 
} from 'lucide-react';

export default function SummaryCard({ summary, filename }) {
  const [copied, setCopied] = useState(false);
  const [checkedItems, setCheckedItems] = useState({});

  if (!summary) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([summary], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${filename || 'meeting'}_summary.md`;
    link.click;
    URL.revokeObjectURL(url);
  };

  const toggleCheck = (index) => {
    setCheckedItems(prev => ({
      ...prev,
      [index]: !prev[index]
    }));
  };

  // Helper to parse sections cleanly
  const parseSections = (text) => {
    const lines = text.split('\n');
    const sections = [];
    let currentSection = { title: 'Overview', lines: [] };

    for (const line of lines) {
      if (line.startsWith('## ') || line.startsWith('### ')) {
        if (currentSection.lines.length > 0 || currentSection.title !== 'Overview') {
          sections.push(currentSection);
        }
        currentSection = {
          title: line.replace(/^#+\s*/, '').trim(),
          lines: []
        };
      } else {
        currentSection.lines.push(line);
      }
    }
    sections.push(currentSection);
    return sections;
  };

  const sections = parseSections(summary);

  const getSectionIcon = (title) => {
    const lower = title.toLowerCase();
    if (lower.includes('decision')) return <ShieldCheck className="w-5 h-5 text-amber-400" />;
    if (lower.includes('action') || lower.includes('task')) return <ListChecks className="w-5 h-5 text-emerald-400" />;
    if (lower.includes('executive') || lower.includes('summary')) return <Sparkles className="w-5 h-5 text-blue-400" />;
    return <FileText className="w-5 h-5 text-slate-400" />;
  };

  return (
    <div className="glass-panel-glow rounded-2xl p-6 sm:p-8 border border-emerald-500/30">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-slate-800">
        <div className="flex items-center space-x-3">
          <div className="p-2 rounded-xl bg-gradient-to-br from-emerald-500/20 to-teal-500/20 text-emerald-400 border border-emerald-500/30">
            <Sparkles className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-white tracking-tight">Structured Meeting Summary</h2>
            <p className="text-xs text-slate-400 mt-0.5">
              Generated by Groq <span className="text-emerald-400 font-mono">llama-3.3-70b-versatile</span>
            </p>
          </div>
        </div>

        {/* Action buttons */}
        <div className="flex items-center space-x-2">
          <button
            onClick={handleCopy}
            className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 border border-slate-800 text-slate-200 text-xs font-medium transition-colors"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied' : 'Copy MD'}</span>
          </button>

          <button
            onClick={handleDownload}
            className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 border border-slate-800 text-slate-200 text-xs font-medium transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download</span>
          </button>
        </div>
      </div>

      {/* Structured Sections Content */}
      <div className="mt-6 space-y-6">
        {sections.map((section, sIdx) => {
          const sectionContent = section.lines.join('\n').trim();
          if (!sectionContent && section.title === 'Overview') return null;

          const isActionSection = section.title.toLowerCase().includes('action');
          const isDecisionSection = section.title.toLowerCase().includes('decision');

          return (
            <div 
              key={sIdx} 
              className={`p-5 rounded-xl border transition-all ${
                isDecisionSection 
                  ? 'bg-amber-950/10 border-amber-500/30 shadow-sm'
                  : isActionSection
                  ? 'bg-emerald-950/10 border-emerald-500/30 shadow-sm'
                  : 'bg-slate-900/50 border-slate-800/80'
              }`}
            >
              <div className="flex items-center space-x-2.5 mb-3">
                {getSectionIcon(section.title)}
                <h3 className={`text-base font-bold tracking-tight ${
                  isDecisionSection 
                    ? 'text-amber-300' 
                    : isActionSection 
                    ? 'text-emerald-300' 
                    : 'text-slate-100'
                }`}>
                  {section.title}
                </h3>
              </div>

              {isActionSection ? (
                <div className="space-y-2 text-sm text-slate-300">
                  {section.lines.filter(l => l.trim().length > 0).map((line, lIdx) => {
                    const itemKey = `${sIdx}-${lIdx}`;
                    const isChecked = checkedItems[itemKey] || false;
                    const cleanText = line.replace(/^-\s*\[[ x]\]\s*/i, '').replace(/^-\s*/, '');

                    return (
                      <div 
                        key={lIdx}
                        onClick={() => toggleCheck(itemKey)}
                        className={`flex items-start space-x-3 p-2.5 rounded-lg cursor-pointer transition-colors ${
                          isChecked 
                            ? 'bg-emerald-900/20 text-slate-400 line-through' 
                            : 'hover:bg-slate-850 bg-slate-900/40 text-slate-200'
                        }`}
                      >
                        <div className={`mt-0.5 flex-shrink-0 w-4 h-4 rounded flex items-center justify-center border transition-colors ${
                          isChecked ? 'bg-emerald-500 border-emerald-500 text-slate-950' : 'border-slate-600 bg-slate-950'
                        }`}>
                          {isChecked && <Check className="w-3 h-3 stroke-[3]" />}
                        </div>
                        <span className="text-xs sm:text-sm leading-relaxed">{cleanText}</span>
                      </div>
                    );
                  })}
                </div>
              ) : (
                <div className="text-xs sm:text-sm text-slate-300 leading-relaxed whitespace-pre-wrap">
                  {sectionContent}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
